config/routes.rb
Findatech::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}

  root :to => "home#index"

  resources :users do
    collection do
      get :dashboard
      get :settings
      post :delete_photo
      post :get_my_schedule
      post :get_availability
      post :set_availability
      post :update_availability
      post :remove_availability
      get :search
    end
    get :availability
    put :change_photo
    get :profile
    get :schedule_appointment
    get :schedule
    post :update_schedule
    post :sync_to_gcal
  end

  #admin routes
  match 'admins/dashboard/' => 'admins/admin#dashboard'
  namespace :admins do
     resources :users do
       post :reset_password
       post :lock_user
       post :unlock_user
       get :set_featured_tech
     end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :reverse_geocode
  has_many :user_roles
  has_many :roles, :through => :user_roles
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username,
                  :city, :state, :zip, :rate, :distance, :timezone, :full_name, :profile_picture
                  
  validates_format_of :email, :with  => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :allow_blank => false, :if => :email_changed?
  validates :email, :uniqueness => { :message => "is already taken" }
  validates :username, :uniqueness => { :message => "is already taken" }
  validates_presence_of :email, :username, :password, :password_confirmation, :on => :create
  validates_presence_of :city, :state, :zip, :full_name
  validates_confirmation_of :password, :on => :create
  
  has_attached_file :profile_picture, :styles => { :large => "218x218#", :medium => "150x150#", :thumb => "50x50#", :tiny => "28x28#" },
                                      :url => "/system/profile_pictures/:id/:style/:normalized_file_name.:extension",
                                      :default_url => "/assets/avatar/missing_:style.jpg",
                                      :path => ":rails_root/public/system/profile_pictures/:id/:style/:normalized_file_name.:extension"
  
  acts_as_mappable :default_units => :miles, 
                   :default_formula => :sphere, 
                   :distance_field_name => :distance_from,
                   :lat_column_name => :lat,
                   :lng_column_name => :lon
                   
  Paperclip.interpolates :normalized_file_name do |attachment, style|
    attachment.instance.normalized_file_name
  end

  def normalized_file_name
    Digest::MD5.hexdigest(self.profile_picture_file_name+self.id.to_s)
  end
                   
  def reverse_geocode
    if !self.city.nil? and !self.state.nil?
      results = Geokit::Geocoders::GoogleGeocoder.geocode(self.city+', '+self.state)
      if !results.nil?
        self.lat = results.lat
        self.lon = results.lng
      end
    end
  end
  
  def role?(role)
    role = Role.find_by_role(role)
    if role and self.roles.include?(role)
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:profile, :search]
  load_and_authorize_resource
  skip_load_and_authorize_resource :only => [:profile, :search]
  respond_to :html, :json
  
  # dashboard page
  #   -landing page when a user signs in
  #
  def dashboard

  end
  
  # settings page
  #   -page for a user to update their profile and settings
  #
  # * *Args*    :
  #   - +sort+ -> sort testimonials (1 for ASC)
  #   - +page+ -> used with pagination
  #   - +error+ -> facebook connect error (if applicable)
  # * *Returns* :
  #   - User attributes as json object
  #
  def settings
    @user = current_user
    
    respond_to do |format|
      format.json { render :json => @user }
      format.html { render :layout => 'home'}
    end
  end

  # update action
  #   -json action to update a user's settings
  #
  # * *Args*    :
  #   - +user=>**+ -> User's Attributes
  # * *Returns* :
  #   - User's attributes as a json object
  # * *Raises* :
  #   - +Errors+ -> if the user object fails to save
  #
  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      sign_in(@user, :bypass => true)
      redirect_to dashboard_users_path, :notice => 'Settings updated successfully!'
    else
      render 'settings', :layout => 'home'
    end
  end
  
  # delete_photo action
   #   -form to upload a remove picture as a user's avatar
   #
   # * *Returns* :
   #   - medium and large urls generated by paperclip (default avatars)
   # * *Raises* :
   #   - +0+ -> if the delete fails
   #
  def delete_photo
    user = User.find(current_user.id)
    user.profile_picture = nil
    if user.save
      render :json => {
        :medium => user.profile_picture.url(:medium),
        :large => user.profile_picture.url(:large)
      }
    else
      render :json => 0
    end
  end

  # schedule_appointment action
  #   -page where a user schedules an appointment with a tech
  #
  # * *Args*    :
  #   - +tech_id+ -> Technician's ID
  # * *Returns* :
  #   - the schedule page with a @tech assign
  # * *Raises* :
  #   - +redirection+ -> if the tech's ID is your own ID
  #
  def schedule_appointment
    @appoitnment = Appointment.new
    @tech = User.find(params[:tech_id])
    if current_user.id == params[:user_id].to_i
      redirect_to settings_users_path
    end
  end
  
  # update_schedule action
  #   -retrieves the gurus available schedule based on duration and month
  #
  # * *Args*    :
  #   - +duration+ -> length of desired wurqout (in minutes)
  #   - +month+ -> month of gurus availability
  #   - +year+ -> year of gurus availability
  # * *Returns* :
  #   - the gurus availability spans in a json array
  #
  def update_schedule
    @user = User.find(params[:user_id])
    @data = @user.get_schedule_availability(params, current_user, false, 0)
    render :json => @data
  end

  # search action
  #   -searches wurqers and gurus when scheduling a wurqout
  #
  # * *Args*    :
  #   - +user=>gender+ -> Desired gender of co-wurqer or guru
  # * *Returns* :
  #   - An array of user's that match the given criteria
  #
  def search
    if params[:address].nil?
      @techs = []
    elsif !params[:address].blank? and !params[:city].blank? and params[:state]
      origin = [params[:address], params[:city], params[:state]].join(', ')
    elsif !params[:zip].blank?
      origin = params[:zip]
    elsif current_user.lat and current_user.lon
      origin = [current_user.lat, current_user.lon]
    else
      @error = 'Unable to determine your location'
    end
    
    if origin
      @techs = User.within(params[:miles].to_i, :origin => origin).paginate(:page => params[:page], :per_page => 10, :joins => :roles, :conditions => ["roles.role = 'tech' and users.active = 1 and distance <= users.distance"]).order('created_at DESC')
    end  
  end

  # profile page
  #   -page displaying a given user's profile
  #
  # * *Args*    :
  #   - +user_id+ -> Given user's ID
  # * *Returns* :
  #   - profile page with @user assign
  #
  def profile
    @user = User.find(params[:user_id])
  end

  # availability page
  #   -page where a guru sets their availability for wurqout sessions
  #
  # * *Returns* :
  #   - the availability page
  # * *Raises* :
  #   - +redirection+ -> if the user is a wurqer, or the guru has no timezone set
  #
  def availability
    if current_user.role?('wurqer')
      redirect_to settings_users_path, :notice => 'Availability scheduling is for Gurus only.'
    elsif current_user.timezone.blank?
      redirect_to settings_users_path, :notice => 'You must set your Timezone to update your schedule.'
    end
  end

  # get_availability action
  #   -retrieve's a guru's current availability to fill in the calendar
  #
  # * *Returns* :
  #   - the gurus availability from now to next month as a json array
  #
  def get_availability
    @user = current_user
    @data = @user.get_availability()
    render :json => {:events => @data, :freebusys => [{:start => DateTime.now - 10.years, :end => DateTime.now, :free => false},
                                                      {:start => DateTime.now + 1.month, :end => DateTime.now+10.years, :free => false}]}
  end

  # set_availability action
  #   -action to set a guru's availability
  #
  # * *Args*    :
  #   - +start+ -> Start date/time for availability
  #   - +end+ -> End date/time for availability
  #   - +recurring+ -> true if the availability recurs each week
  # * *Returns* :
  #   - the new event's ID for the calendar
  #
  def set_availability
    @user = current_user
    @start = DateTime.parse(params[:start])
    @end = DateTime.parse(params[:end])
    if params[:recurring] == 'true'
      @start = @start.in_time_zone('UTC')
      @end = @end.in_time_zone('UTC')
      # destroy any current recurring availabilities at this time
      @user.guru_recurring_availabilities.select{|avail| avail.weekday == @start.wday and ((Time.parse(avail.start_time.strftime('%T')) > Time.parse(@start.strftime('%T')) and Time.parse(avail.start_time.strftime('%T')) < Time.parse(@end.strftime('%T'))) or (Time.parse(avail.end_time.strftime('%T')) > Time.parse(@start.strftime('%T')) and Time.parse(avail.end_time.strftime('%T')) < Time.parse(@end.strftime('%T')))) }.each do |avail|
        avail.destroy
      end
      @av = GuruRecurringAvailability.create(:start_time => @start, :end_time => @end, :weekday => @start.in_time_zone(current_user.timezone).wday, :user_id => @user.id)
      @event_id = 'recur_'+@av.id.to_s
    else
      # destroy any current scheduled availabilities at this date/time
      @user.guru_scheduled_availabilities.where(["(start_date > ? and start_date < ?) or (end_date > ? and end_date < ?)", @start, @end, @start, @end]).each do |avail|
        avail.destroy
      end
      @av = GuruScheduledAvailability.create(:start_date => @start, :end_date => @end, :user_id => @user.id)
      @event_id = @av.id
    end
    render :json => {:event_id => @event_id}
  end

  # update_availability action
  #   -action to update an existing guru availability
  #
  # * *Args*    :
  #   - +event_id+ -> ID t=of the current event (availability)
  #   - +slot=>start+ -> Start date/time for availability
  #   - +slot=>end+ -> End date/time for availability
  #   - +recurring+ -> true if the availability recurs each week
  # * *Returns* :
  #   - the updated event's ID for the calendar
  #
  def update_availability
    @user = current_user
    @start = DateTime.parse(params[:slot][:start])
    @end = DateTime.parse(params[:slot][:end])
    if params[:recurring] == 'true'
      if params[:event_id].index('recur')
        #updates a recurring event
        @avail = GuruRecurringAvailability.find(params[:event_id].split('_')[1])
        @avail.update_attributes({:start_time => @start, :end_time => @end, :weekday => @start.wday})
        @event_id = params[:event_id]
      else
        #updates a recurring event to a scheduled event
        @avail = GuruScheduledAvailability.find(params[:event_id])
        @avail.destroy
        @user.guru_recurring_availabilities.select{|avail| avail.weekday == @start.wday and ((Time.parse(avail.start_time.in_time_zone(current_user.timezone).strftime('%T')) > Time.parse(@start.strftime('%T')) and Time.parse(avail.start_time.in_time_zone(current_user.timezone).strftime('%T')) < Time.parse(@end.strftime('%T'))) or (Time.parse(avail.end_time.in_time_zone(current_user.timezone).strftime('%T')) > Time.parse(@start.strftime('%T')) and Time.parse(avail.end_time.in_time_zone(current_user.timezone).strftime('%T')) < Time.parse(@end.strftime('%T')))) }.each do |avail|
          avail.destroy
        end
        @av = GuruRecurringAvailability.create(:start_time => @start, :end_time => @end, :weekday => @start.wday, :user_id => @user.id)
        @event_id = 'recur_'+@av.id.to_s
      end
    else
      if params[:event_id].index('recur')
        # updates a scheduled event to a recurring event
        @avail = GuruRecurringAvailability.find(params[:event_id].split('_')[1])
        @avail.destroy
        @av = GuruScheduledAvailability.create(:start_date => @start, :end_date => @end, :user_id => @user.id)
        @event_id = @av.id
      else
        # updates a scheduled event
        @avail = GuruScheduledAvailability.find(params[:event_id])
        @user.guru_scheduled_availabilities.where(["id != #{@avail.id} and ((start_date > ? and start_date < ?) or (end_date > ? and end_date < ?))", @start, @end, @start, @end]).each do |avail|
          avail.destroy
        end
        @avail.update_attributes({:start_date => @start, :end_date => @end})
        @event_id = @avail.id
      end
    end
    render :json => {:event_id => @event_id}
  end

  # remove_availability action
  #   -action to delete a guru's availability
  #
  # * *Args*    :
  #   - +av_id+ -> ID of the availability
  # * *Returns* :
  #   - 1 if the deletion was successful
  #
  def remove_availability

app/helpers/users_helper.rb
module UsersHelper
  def state_list
    [
      [ "State", "" ],
      [ "Alabama", "AL" ], 
      [ "Alaska", "AK" ], 
      [ "Arizona", "AZ" ], 
      [ "Arkansas", "AR" ], 
      [ "California", "CA" ], 
      [ "Colorado", "CO" ], 
      [ "Connecticut", "CT" ], 
      [ "Delaware", "DE" ], 
      [ "District Of Columbia", "DC" ], 
      [ "Florida", "FL" ], 
      [ "Georgia", "GA" ], 
      [ "Hawaii", "HI" ], 
      [ "Idaho", "ID" ], 
      [ "Illinois", "IL" ], 
      [ "Indiana", "IN" ], 
      [ "Iowa", "IA" ], 
      [ "Kansas", "KS" ], 
      [ "Kentucky", "KY" ], 
      [ "Louisiana", "LA" ], 
      [ "Maine", "ME" ], 
      [ "Maryland", "MD" ], 
      [ "Massachusetts", "MA" ], 
      [ "Michigan", "MI" ], 
      [ "Minnesota", "MN" ], 
      [ "Mississippi", "MS" ], 
      [ "Missouri", "MO" ], 
      [ "Montana", "MT" ], 
      [ "Nebraska", "NE" ], 
      [ "Nevada", "NV" ], 
      [ "New Hampshire", "NH" ], 
      [ "New Jersey", "NJ" ], 
      [ "New Mexico", "NM" ], 
      [ "New York", "NY" ], 
      [ "North Carolina", "NC" ], 
      [ "North Dakota", "ND" ], 
      [ "Ohio", "OH" ], 
      [ "Oklahoma", "OK" ], 
      [ "Oregon", "OR" ], 
      [ "Pennsylvania", "PA" ], 
      [ "Rhode Island", "RI" ], 
      [ "South Carolina", "SC" ], 
      [ "South Dakota", "SD" ], 
      [ "Tennessee", "TN" ], 
      [ "Texas", "TX" ], 
      [ "Utah", "UT" ], 
      [ "Vermont", "VT" ], 
      [ "Virginia", "VA" ], 
      [ "Washington", "WA" ], 
      [ "West Virginia", "WV" ], 
      [ "Wisconsin", "WI" ], 
      [ "Wyoming", "WY" ]
    ]
  end
end

app/views/users/_emergency_contact_fields.html.erb
<% id = f.object.id.nil? ? 'replace_id' : f.object.id %>
	
<div class="fields well">
    <ul class="split split2 unstyled control-group">
        <li>
            <%= f.label :first_name %>
            <%= f.text_field :first_name, 'data-id' => id, :class => 'autosave' %>
        </li>
        <li>
            <%= f.label :last_name %>
            <%= f.text_field :last_name, 'data-id' => id,  :class => 'autosave' %>  
        </li>
    </ul>
    <ul class="split split2 unstyled">
        <li>
            <%= f.label :relationship, 'Relationship to you' %>
            <%= f.text_field :relationship, 'data-id' => id,  :class => 'autosave'  %>
        </li>
        <li>
            <%= f.label :phone_number, 'Phone Number' %>
            <%= f.text_field :phone_number, 'data-id' => id,  :class => 'autosave' %>
        </li>
    </ul>  
    <%= link_to_remove_emergency_contact '<i class="icon-remove"></i>'.html_safe, f, :class => 'btn btn-mini remove' %>
</div>

app/views/users/_search_wurqout_fields.html.erb
<div class="fields">
    <%= f.text_field :interest, :class => 'interest', 'data-id' => 'replace_id'%>
    <label><%= f.object.interest %><%= link_to_remove_interests '<i class="icon-remove"></i>'.html_safe, f, :class => 'btn btn-mini' %></label>
</div>

app/views/users/_user_interest_fields.html.erb
<div class="fields">
    <%= f.text_field :interest, :class => 'interest', :readonly => true, :disabled => true, 'data-id' => 'replace_id'%>
    <label><%= f.object.interest %><%= link_to_remove_interests '<i class="icon-remove"></i>'.html_safe, f, :class => 'btn btn-mini' %></label>
</div>

app/views/users/availability.html.erb
<div class="calendar-default">
    <div class="wc-top-header header-title">Your Availability</div>
    <div id="calendar"></div>
    
    <input type="hidden" id="user_tz_offset" value="<%= DateTime.now.in_time_zone(current_user.timezone).strftime('%z') %>"/>
    <div id="event_edit_container">
        <div class="arrow"></div>
        <div class="wc-dialog-title"></div>
        <form class="form-calendar-modal">
            <input type="hidden" />
            <p class="centered"><small>Date: <span class="date_holder"></span></small></p>
            <ul class="split2 unstyled">
                <li>
                    <label for="start">Start Time</label>
                    <select name="start"><option value="">Select Start Time</option></select>
                </li>
                <li>
                    <label for="end">End Time</label>
                    <select name="end"><option value="">Select End Time</option></select>
                </li>
            </ul>
            <div class="control-group">
                <label class="checkbox inline" for="recurring">
                    <input type="checkbox" name="recurring" id="recurring" value="true"> Repeat every week
                </label>
            </div>
        </form>
    </div>
</div>

app/views/users/dashboard.html.erb
<div class="row">
    <div id="dashboard_right">
    	Dashboard!
    </div>
</div>

app/views/users/profile.html.erb
<div>
	<% if @user.profile_picture.present? %><p><%= image_tag @user.profile_picture.url(:medium)%></p><% end %>
    <h2><%= @user.full_name %> - <%= @user.username %></h2>
	
	<p>Location: <%= @user.city %>, <%= @user.state %> <%= @user.zip %></p>
	
	<% if !@user.bio.blank? and @user.role?('tech') %>
		<h4>About this Tech</h4>
		<p><%= @user.bio %></p>
	<% end %>
</div>

app/views/users/schedule.html.erb
<%= render 'users/shared/user_sidebar' %>

<input type="hidden" id="user_id" value="<%= current_user.id %>"/>

<div id="schedule_right">
    <input type="hidden" id="calendar_year" value="<%= DateTime.now.in_time_zone(current_user.timezone).year %>"/>
    <input type="hidden" id="calendar_month" value="<%= DateTime.now.in_time_zone(current_user.timezone).month %>"/>
    <div class="calendar-default push">
        <div class="header-title">My Schedule</div>
        <div class="month-nav">
            <button id="prev_month_schedule" class="arrow"></button>
            <div class="title">
                <span id="month_name"><%= Date::MONTHNAMES[DateTime.now.in_time_zone(current_user.timezone).month]%></span> <span id="year"><%= DateTime.now.in_time_zone(current_user.timezone).year.to_s %></span>
            </div>
            <button id="next_month_schedule" class="arrow"></button>
        </div>
        <div class="cal-cont">
            <table id="my_schedule_calendar" class="table table-calendar">
                <thead>
                    <tr>
                        <th>SUN</th>
                        <th>MON</th>
                        <th>TUE</th>
                        <th>WED</th>
                        <th>THU</th>
                        <th>FRI</th>
                        <th>SAT</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
            <ul class="legend">
                <li><i class="icon14-dot-bl"></i> Scheduled wurqout with guru</li>
                <li><i class="icon14-dot-gr"></i> Scheduled wurqout with friend</li>
            </ul>
        </div>
    </div>
</div>
<%= link_to 'Sync to Google Calendar', '', :class => 'sync_gcal btn btn-green pull-right' if current_user.gmail_email.present? and current_user.gmail_calendar_name.present? %>
<div id="planner-history" class="push">
    <% if @upcoming_sessions.size > 0 %>
    	<h3>Upcoming</h3>
    	<ul class="unstyled">
    	<% @upcoming_sessions.sort{|a, b| b <=> a}.each_with_index do |ws, index| %>
    		<li class="session_row<%= ' hidden_row hide' if index > 4 %>" data-id="<%=ws.id%>" data-type="<%= ws.attributes['guru_id'].nil? ? 'cowurq' : 'guru' %>">
    			<% other_person = (ws.attributes['guru_id'].nil? ? (current_user == ws.user ? ws.cowurqer : ws.user) : (current_user == ws.guru ? ws.wurqer : ws.guru)) %>
    			<p class="date"><%= ws.start_date.in_time_zone(current_user.timezone).strftime('%D') %></p>
    			<div>
    			    <div class="pull-right hide actions">
    				    <%= link_to 'Send Message', '#', :class => 'add_session_note btn' %>
    				    <%= link_to 'Cancel Session', (ws.attributes['guru_id'].nil? ? cowurq_session_cancel_session_path(ws) : wurqout_session_cancel_session_path(ws)), :class => 'btn', :confirm => 'Are you sure you want to cancel this session?' %>
    				</div>
    				<%= image_tag other_person.profile_picture.url(:tiny) %> <%= ws.start_date.in_time_zone(current_user.timezone).strftime('%l:%M%p') %> - <%= ws.session_type.blank? ? 'Wurqout' : ws.session_type %> with 
    				<%= link_to (other_person.member_name.blank? ? other_person.username : other_person.member_name), user_profile_path(other_person) %>
    			</div>
    		</li>
    	<% end %>
    	</ul>
    	<% if @upcoming_sessions.size > 5 %>
    		<p class="centered"><%= link_to 'Load more upcoming', "", :id => 'load_more_upcoming', :class => 'btn' %></p>
    	<% end %>	
    <% end %>

    <% if @ws_history.size > 0 %>
    	<h3>Wurqout History</h3>
    	<ul class="unstyled">
    	<% @ws_history.each do |ws| %>
    		<li class="session_row" data-id="<%=ws.id%>" data-type="guru">
    			<% other_person = (current_user == ws.guru ? ws.wurqer : ws.guru) %>
    			<p class="date"><%= ws.start_date.in_time_zone(current_user.timezone).strftime('%D') %></p>
    			<div>
    			    <div class="pull-right hide actions">
    				    <%= link_to 'Send Message', '#', :class => 'add_session_note btn' %>
    				    <%= link_to 'View Notes', wurqout_session_path(ws), :class => 'btn' %>
    				</div>
    				<%= image_tag other_person.profile_picture.url(:tiny) %> <%= ws.start_date.in_time_zone(current_user.timezone).strftime('%l:%M%p') %> - <%= ws.session_type.blank? ? 'Wurqout' : ws.session_type %> with 
    				<%= link_to (other_person.member_name.blank? ? other_person.username : other_person.member_name), user_profile_path(other_person) %>
    			</div>
    		</li>
    	<% end %>
        </ul>
    	<%= will_paginate @ws_history, :param_name => 'guru_sessions', :renderer => BootstrapPagination::Rails %>
    <% end %>

    <% if @cs_history.size > 0 %>
    	<h3>Co-Wurqout History</h3>
    	<ul class="unstyled">
    	<% @cs_history.each do |ws| %>
    		<li class="session_row" data-id="<%=ws.id%>" data-type="cowurq">
    			<% other_person = (current_user == ws.user ? ws.cowurqer : ws.user) %>
    			<p class="date"><%= ws.start_date.in_time_zone(current_user.timezone).strftime('%D') %></p>
    			<div>
    			    <div class="pull-right hide actions">
    				    <%= link_to 'Send Message', '#', :class => 'add_session_note btn' %>
    				    <%= link_to 'View Notes', cowurq_session_path(ws), :class => 'btn' %>
    				</div>
    				<%= image_tag other_person.profile_picture.url(:tiny) %> <%= ws.start_date.in_time_zone(current_user.timezone).strftime('%l:%M%p') %> - <%= ws.session_type.blank? ? 'Wurqout' : ws.session_type %> with 
    				<%= link_to (other_person.member_name.blank? ? other_person.username : other_person.member_name), user_profile_path(other_person) %>
    			</div>
    		</li>
    	<% end %>
        </ul>
    	<%= will_paginate @cs_history, :param_name => 'cowurq_sessions', :renderer => BootstrapPagination::Rails %>
    <% end %>
</div>

<div id="day_modals">
	
</div>

<div id="add_session_notes_modal" class="modal hide fade" data-id="" data-type="">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Send Message</h3>
    </div>
    <div class="modal-body">
        <textarea id="session_note_body"></textarea>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        <button class="btn btn-success" id="my_schedule_submit_note">Submit Message</button>
    </div>
</div>

<div id="sync_modal" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Sync To Google Calendar</h3>
    </div>
    <div class="modal-body">
		<p>Google Email Address: <%= current_user.gmail_email %></p>
        Google Password: <input type="password" id="gcal_pw">
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        <button class="btn btn-success" id="submit_gcal_sync">Sync Calendar</button>
    </div>
</div>

<script>
	$(function(){
		getMySchedule();
	});
</script

app/views/users/search.html.erb
    <div class="widget-title"><h3 class="green">Narrow Your Results</h3></div>
    <div class="widget">
       
        <%= form_tag search_users_path, :method => :get, :class => 'form-search' do |f|%>
            <p>Within <%= select_tag 'miles', options_for_select((10..100).to_a.select{|n| n%10 == 0}) %> of ..<br></p>
			<p><%= radio_button_tag 'location', 'saved', true, :class => 'location' %> My saved location (<%= current_user.city + ', ' + current_user.state %>)</p>
			<p><%= radio_button_tag 'location', 'custom', false, :class => 'location' %> <%= text_field_tag 'address', nil, :placeholder => 'Address' %> 
			<%= text_field_tag 'city', nil, :placeholder => 'City' %> <%= select_tag 'state', options_for_select(state_list) %> <%= text_field_tag 'zip', nil, :placeholder => 'Zip Code' %> </p>

            <div class="centered">
                <%= submit_tag 'Search', :class => 'btn btn-green' %>
            </div>
    
        <% end %>
     </div>

<% if !@techs.blank? %>
    <ul id="search_results" class="unstyled">
        <% @techs.each do |u| %>
            <li>
                <%= image_tag u.profile_picture.url(:medium), :class => 'user-photo' %>
                <h4><%= link_to (u.full_name + ' &raquo;').html_safe, user_profile_path(u) %></h4>
                <dl class="rate">
                    <dt>Rate :</dt>
                </dl>
                <%= link_to 'Schedule an Appointment', schedule_appointment_users_path(:tech_id => u.id), :class => 'btn' %>
            </li>
        <% end %>
    </ul>
    <%= will_paginate @techs, :renderer => BootstrapPagination::Rails %>
<% elsif !params[:address].nil? %>
    <p>There are currently no techs in your area.</p>
<% end %>