config/routes.rb
Findatech::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}

  root :to => "home#index"

  resources :users do
    collection do
      get :dashboard
      get :settings
      post :delete_photo
      post :get_my_schedule
      post :get_availability
      post :set_availability
      post :update_availability
      post :remove_availability
      get :search
    end
    get :availability
    put :change_photo
    get :profile
    get :schedule_appointment
    get :schedule
    post :update_schedule
    post :sync_to_gcal
  end

  #admin routes
  match 'admins/dashboard/' => 'admins/admin#dashboard'
  namespace :admins do
     resources :users do
       post :reset_password
       post :lock_user
       post :unlock_user
       get :set_featured_tech
     end
  end
  
end

app/views/users/shared/settings/_account_settings.html.erb
<div class="control-group spaced">
    <%= label_tag "Emails", nil, :class => "big" %>
    <div class="push">
        <%= f.label :email_me_website_news, :class => "checkbox" do %> 
            <%= f.check_box :email_me_website_news, :class => 'autosave' %> Email me with website news
        <% end %>

        <%= f.label :email_wurqout_request, :class => "checkbox" do %> 
            <%= f.check_box :email_wurqout_request, :class => 'autosave' %> Email me when I get a wurqout request
        <% end %>

        <%= f.label :email_request_to_join, :class => "checkbox" do %> 
            <%= f.check_box :email_request_to_join, :class => 'autosave' %> Email me when someone requests to join my netwurq
        <% end %>

        <%= f.label :email_cancellation_request_guru, :class => "checkbox" do %>   
            <%= f.check_box :email_cancellation_request_guru, :class => 'autosave' %> Email me when I get a cancellation or time change from a guru
        <% end %>
    </div>
</div>
<div class="control-group spaced">
    <%= label_tag nil, "Connect", :class => "big" %>
    <div class="push">
        <% if !current_user.fb_token.nil? %>
            <%= link_to 'Disconnect Facebook', users_disconnect_facebook_path, :class => "fb-btn" %>
        <% else %>
            <%= link_to "Connect with Facebook", users_connect_facebook_path, :class => "fb-popup fb-btn", :"data-width" => 600, :"data-height" => 400 %>
        <% end %>
    </div>
</div>
<div class="control-group spaced">
    <%= label_tag nil, "Google Calendar<br><small>Sync wurqouts to google calendar</small>".html_safe, :class => "big" %>
    <div class="push pad">
        <%= f.label :gmail_email, "Gmail email address" %> 
        <%= f.text_field :gmail_email, :class => 'autosave' %>

        <%= f.label :gmail_calendar_name %> 
        <%= f.text_field :gmail_calendar_name, :class => 'autosave' %>
    </div>
</div>
<div class="control-group spaced">
    <%= label_tag nil, "Change Password", :class => "big" %>
    <div class="push pad">
        <%= f.label :password %> 
        <%= f.password_field :password, :autocomplete => 'off' %>

        <%= f.label :password_confirmation %> 
        <%= f.password_field :password_confirmation, :autocomplete => 'off', :class => 'autosave' %>
    </div>
</div>
<div class="control-group spaced">
    <%= label_tag "Privacy", nil, :class => "big" %>
    <div class="push">
        <%= f.label :email_me_website_news, :class => "checkbox" do %> 
            <%= f.check_box :email_me_website_news, :class => 'autosave' %> Email me with website news
        <% end %>
    </div>
</div>

app/views/users/shared/settings/_billing_payments.html.erb
<div class="control-group spaced">
    <%= label_tag 'Your Billing Information', nil, :class => "big" %>
    <br>
    <div class="control-group push">
	    <%= f.label :paypal_email, "Paypal Email Address" %>
	    <%= f.text_field :paypal_email, :class => 'autosave' %>
	</div>
</div>

<div class="control-group spaced">
    <%= label_tag 'Your Current Statement', nil, :class => "big" %>
    <div class="control-group">
		<table class="table table-billing">
			<thead>
				<tr>
					<th colspan="2">Person</th>
					<th>Session</th>
					<th>Fee</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				<% total = 0 %>
				<% @user.guru_wurqout_sessions.select{|w| w.status == 'completed' and !w.payment.dispersed and !w.payment.refunded }.each do |w| %>
					<tr>
						<td class="avatar"><%= image_tag w.wurqer.profile_picture.url(:tiny) %></td>
						<td><%= w.wurqer.member_name.present? ? w.wurqer.member_name : w.wurqer.username %></td>
						<td><%= ((w.end_date - w.start_date)/60).to_i.to_s+'min: '+number_to_currency(w.cost) %></td>
						<td>(<%= number_to_currency((w.cost.to_f/10)) %>)</td>
						<td><%= number_to_currency(w.cost - (w.cost.to_f/10)) %></td>
					</tr>
					<% total += (w.cost - (w.cost.to_f/10)) %>
				<% end %>
			</tbody>
			<tfoot>
				<tr>
					<% if total == 0 %>
						<td></td>
						<td colspan="3"><i>no unpaid wurqout sessions</i></td>
						<td></td>
					<% else %>
						<td colspan="3"></td>
						<td colspan="3">Total as of <%= DateTime.now.in_time_zone(@user.timezone || 'UTC').strftime('%D') %>: <strong><%= number_to_currency(total) %></strong></td>
					<% end %>
				</tr>
			</tfoot>
		</table>
	</div>
</div>

<div class="control-group spaced">
    <%= label_tag 'Your Past and Pending Payments', nil, :class => "big" %>
    <div class="control-group">
		<table class="table table-billing">
			<thead>
				<tr>
					<th>Payment Date</th>
					<th>Status</th>
					<th>Total</th>
					<th>View</th>
				</tr>
			</thead>
			<tbody>
				<% @user.guru_payments.order('created_at desc').each_with_index do |p, index| %>
					<tr class="<%= 'hidden_row' if index > 5 %>">
						<td><%= p.created_at.in_time_zone(@user.timezone).strftime('%D') %></td>
						<td>COMPLETE</td>
						<td><%= number_to_currency(p.amount) %></td>
						<td><%= link_to 'View', '', :class => 'btn guru_payment', :'data-payment' => p.id %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<% if @user.guru_payments.size > 6 %><p class="pull-right"><a href="" id="more_payments">load more</a></p><% end %>
	</div>
</div>

<% @user.guru_payments.each do |p| %>
	<div id="payment_modal_<%= p.id %>" class="modal hide fade">
		<div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	        <h3>Statement for <%= p.created_at.in_time_zone(@user.timezone).strftime('%D') %></h3>
	    </div>
	    <div class="modal-body">
	        <div class="section overview">
	            <p>Date: <%= p.created_at.in_time_zone(@user.timezone).strftime('%D') %> | Status: COMPLETE</p>
	        </div>
			<table class="table table-striped">
				<thead>
					<tr>
						<td>Person</td>
						<td>Session</td>
						<td>Fee</td>
						<td>Total</td>
					</tr>
				</thead>
				<tbody>
					<% total = 0 %>
					<% p.payments.each do |p| %>
						<tr>
							<td><%= image_tag p.wurqout_session.wurqer.profile_picture.url(:tiny) %><%= p.wurqout_session.wurqer.member_name.present? ? p.wurqout_session.wurqer.member_name : p.wurqout_session.wurqer.username %></td>
							<td><%= ((p.wurqout_session.end_date - p.wurqout_session.start_date)/60).to_i.to_s+'min: '+number_to_currency(p.amount) %></td>
							<td>(<%= number_to_currency((p.amount.to_f/10)) %>)</td>
							<td><%= number_to_currency(p.amount - (p.amount.to_f/10)) %></td>
						</tr>
						<% total += (p.amount - (p.amount.to_f/10)) %>
					<% end %>
				</tbody>
				<tfoot>
					<tr>
						<td colspan="2"></td>
						<td colspan="2">Total: <%= number_to_currency(total) %></td>
					</tr>
				</tfoot>
			</table>
	    </div>
	</div>
<% end %>

app/views/users/shared/settings/_interests.html.erb
<div class="control-group spaced">
    <%= label_tag title, nil, :class => "big" %>
    <div class="push">
        <div class="input-append">
            <input id="autocomplete_interest" name="user_interest" size="30" type="text" />
            <span class="add-on"><i class="icon-search"></i></span>
        </div>
        <%= link_to_add_interest_fields 'Add'.html_safe, f, :user_interests, :class => 'btn hide', :id => 'add_interest_button' %>
        <div id="user_interests">
           
        </div>
    </div>
</div>

app/views/users/shared/settings/_profile_details.html.erb
<p class="help">
    <% if @user.role?('guru') %>
        <em>Profile details are kept private. Only your name is shown unless you make more public. It is recommended that you make as much of your profile information public to better assist wurqers with finding you.</em>
    <% else %>
        <em>Profile details are kept private. Only your first name is shown unless you make more public.</em>
    <% end %>
</p>

<div class="control-group">
    <%= f.label :member_name, "Your Name", :class => "big" %>
    <div class="push">
        <%= f.text_field :member_name, :class => 'autosave' %>
    </div>
</div>

<div class="control-group">
    <%= f.label :profile_picture, "Your Photo"+(@user.role?('guru') ? " and Video" : ""), :class => "big" %>
    <ul id="user_photo_video" class="unstyled">
        <li class="photo">
            <div class="user-photo-progress">
                <%= image_tag @user.profile_picture.url(:medium) %>
            </div>
            <button class="btn">
                Update Photo<%= f.file_field :profile_picture, "data-url" => user_change_photo_path(current_user.id) %>
            </button>
            <button type="button" class="btn" id="user_profile_picture_remove" data-user="<%= current_user.id %>">Delete Photo</button>
        </li>
        <% if @user.role?('guru') %>
        <li class="video">
            <div class="user-video-preview">
                
            </div>
            <div class="link controls">
                <div class="input-append">
                    <%= f.text_field :guru_video_link, :placeholder => 'YouTube or Vimeo link' %>
                    <span class="add-on" rel="tooltip" title="YouTube or Vimeo only"><i class="icon-question-sign"></i></span>
                </div>
                <div class="error"><i></i><label class="message">invalid video url</label></div>
            </div>
        </li>
        <% end %>
    </ul>
</div>

<div class="control-group">
    <%= label_tag nil, 'Your Gender', :class => "big" %>
    <div class="push">
        <%= f.label :gender, :class => 'radio inline' do %>
            <%= f.radio_button :gender, 'male', :class => 'autosave' %> Male
        <% end %>
        <%= f.label :gender, :class => 'radio inline' do %>
            <%= f.radio_button :gender, 'female', :class => 'autosave' %> Female
        <% end %>
    </div>
</div>

<div class="control-group">
    <%= f.label :bio, "User Bio", :class => "big" %>
    <div class="push">
        <span id="bio_count"><%= 500 - (@user.bio.blank? ? 0 : @user.bio.length) %></span><br>
        <%= f.text_area :bio, :class => 'autosave' %>
    </div>
</div>

<div class="control-group">
    <%= f.label :email, "Contact Email", :class => "big" %>
    <div class="push">
        <%= f.text_field :email, :class => 'autosave' %>
    </div>
</div>

<div class="control-group">
    <%= f.label :username, "Username", :class => "big" %>
    <div class="push">
        <%= f.text_field :username, :class => 'autosave' %>
    </div>
</div>

<div class="control-group">
    <%= f.label :timezone, :class => "big" %>
    <div class="push">
		<%= f.collection_select :timezone, ActiveSupport::TimeZone.us_zones, :name, :to_s, {:include_blank => 'Select Timezone'}, { :class => 'autosave' } %>
    </div>
</div>

<div class="control-group">
    <%= f.label :zipcode, :class => "big" %>
    <div class="push">
        <%= f.text_field :zipcode, :class => 'autosave' %>
    </div>
</div>

<div class="control-group">
    <%= f.label :birthday, :class => "big" %>
    <div class="push">
        <%= f.text_field :birthday, :id => "birthday_datepicker", :class => 'autosave' %>

        <%= f.label :birthday_public, :class => "checkbox switcher inline" do %>
            <%= f.check_box :birthday_public, :class => 'switch autosave' %> <span class="on">Public</span><span class="off">Private</span>
        <% end %>
    </div>
</div>

<% if @user.role?('guru') %>
    <%= render 'users/shared/settings/interests', :f => f, :title => 'Specialties' %>
<% end %>

app/views/users/shared/settings/_testimonials.html.erb
<%= label_tag nil, 'Testimonials', :class => "big" %>
<p class="help"><em>Testimonials will be shown on your profile, newest first.</em></p>
<div id="new-testimonial" class="form-testimonial">
    <ul class="split split2 unstyled">
        <li>
            <div class="control-group">
                <%= label_tag 'testimonial[name][new]', 'Name' %>
                <%= text_field_tag 'testimonial[name][new]', nil, :class => 'testimonial-name', :id => 'testimonial_name_new' %>
            </div>
        </li>
        <li>
            <div class="control-group">
                <%= label_tag 'testimonial[date][new]', 'Date' %>
                <%= text_field_tag 'testimonial[date][new]', nil, :class => 'testimonial-date', :id => 'testimonial_date_new' %>
            </div>
        </li>
    </ul>
    <div class="control-group">
        <%= label_tag 'testimonial[body][new]', 'Testimonial' %>
        <%= text_area_tag 'testimonial[body][new]', nil, :class => 'testimonial-body', :id => 'testimonial_body_new' %>
    </div>
    <%= button_tag 'Submit', :type => 'button', :class => 'btn add-testimonial' %>
</div>
<p><span>Order By <select class="testimonial_sort"><option value="0">Newest</option><option value="1"<%= params[:sort].to_i == 1 ? ' selected' : ''%>>Oldest</option></select></span></p>
<table class="table table-testimonials">
    <thead>
        <tr>
            <th>Testimonial</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @testimonials.each_with_index do |testimonial, index| %>
            <tr data-id="<%= testimonial.id %>" class="form-testimonial">
                <td>
                    <div class="view">
                        <p class="meta">
                            <span class="name"><%= testimonial.name %></span> <%= testimonial.date.strftime('%m/%d/%Y') if testimonial.date %>
                        </p>
                        <%= testimonial.body %>
                    </div>
                    <div class="edit hide">
                        <div class="control-group">
                            <%= label_tag 'testimonial[name]', 'Name' %>
                            <%= text_field_tag 'testimonial[name]', testimonial.name, :class => 'testimonial-name', :id => 'testimonial_name_'+testimonial.id.to_s %>
                        </div>
                        <div class="control-group">
                            <%= label_tag 'testimonial[date]', 'Date' %>
                            <%= text_field_tag 'testimonial[date]', testimonial.date, :class => 'testimonial-date', :id => 'testimonial_date_'+testimonial.id.to_s %>
                        </div>
                        <div class="control-group">
                            <%= label_tag 'testimonial[body]', 'Testimonial' %>
                            <%= text_area_tag 'testimonial[body]', testimonial.body, :class => 'testimonial-body', :id => 'testimonial_body_'+testimonial.id.to_s %>
                        </div>
                    </div>
                </td>
                <td class="actions">
                    <%= button_tag 'Edit', :type => 'button', :class => 'btn btn-mini edit-testimonial' %>
                    <%= link_to '<i class="icon-remove"></i>'.html_safe, testimonial_url(testimonial), :remote => true, :method => :delete, :class => 'btn btn-mini delete-testimonial' %>
                    <%= button_tag 'Save', :type => 'button', :class => 'btn btn-mini save-testimonial hide', "data-url" => '/testimonials/'+testimonial.id.to_s %>
                    <%= button_tag 'Cancel', :type => 'button', :class => 'btn btn-mini cancel-testimonial hide' %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= will_paginate @testimonials, :renderer => BootstrapPagination::Rails %>

app/views/users/shared/settings/_vital_information.html.erb
<div id="emergency_contacts" class="control-group">
    <%= label_tag nil, 'Emergency Contact Information', :class => "big" %>
    <%= f.fields_for :emergency_contacts do |uf|%>
        <%= render 'emergency_contact_fields', :f => uf %>
    <% end %>

    <p><%= link_to_add_emergency_contact '<i class="icon-plus"></i>Add additional contact'.html_safe, f, :emergency_contacts, :class => 'btn btn-text' %></p>
</div>

<div class="control-group spaced">
    <p><em>If something happens to me during the wurqout session, I agree to allow Wurqit to show the Guru my emergency contact’s phone number so that they might attempt to contact me in order to ensure proper medical care. The Wurqit team and I will both be notified if this occurs.</em></p>
    <div class="push">
        <%= f.label :emergency_contact_i_agree, :class => "checkbox inline" do %>
            <%= f.check_box :emergency_contact_i_agree, :class => 'autosave' %> I understand and I agree
        <% end %>
    </div>
</div>

<div class="control-group spaced">
    <%= f.label :medical_health_concerns, "Health Concerns", :class => "big" %>
    <p><em>Fill in any concerns your trainer should be aware of prior to training. For example, if you are prone to fainting during heavy exercise, let your trainer know, and agree on a plan of action should this happen.</em></p>
    <div class="push">
        <%= f.text_area :medical_health_concerns, :class => 'autosave' %>
    </div>
</div>

<div id="health_assessment" class="control-group">
    <%= label_tag nil, "Optional Health Assessment", :class => "big" %>
    <p><em>Results are not public, but may be made available to guru if necessary.</em></p>
    <ol class="health-assess">
        <li>
            <%= f.label :medical_heart_condition do %>
                <div class="selection">
                    <%= f.check_box :medical_heart_condition, :class => 'autosave' %> Yes
                </div>Has your doctor ever said that you have a heart condition and that you should only do physical activity recommended by a doctor?
            <% end %>
        </li>
        <li>
            <%= f.label :medical_chest_pains_physical do %>   
                <div class="selection">
                    <%= f.check_box :medical_chest_pains_physical, :class => 'autosave' %> Yes
                </div>Do you feel pain in your chest when you do physical activity?
            <% end %>
        </li>
        <li>
            <%= f.label :medical_chest_pains_not_physical do %>   
                <div class="selection">
                    <%= f.check_box :medical_chest_pains_not_physical, :class => 'autosave' %> Yes
                </div>In the past month, have you had chest pain when you were not doing physical activity?
            <% end %>
        </li>
        <li>
             <%= f.label :medical_lost_balance do %> 
                <div class="selection">
                    <%= f.check_box :medical_lost_balance, :class => 'autosave' %> Yes
                </div>Do you lose your balance because of dizziness or do you ever lose consciousness?
            <% end %>
        </li>
        <li>
             <%= f.label :medical_joint_pain do %>
                <div class="selection">
                    <%= f.check_box :medical_joint_pain, :class => 'autosave' %> Yes
                </div>Do you have a bone or joint problem that could be made worse by a change in your physical activity?
            <% end %>
        </li>
        <li>
             <%= f.label :medical_medication do %>
                <div class="selection">
                    <%= f.check_box :medical_medication, :class => 'autosave' %> Yes
                </div>Is your doctor currently prescribing drugs (for example, water pills) for your blood pressure or heart condition?
            <% end %>
        </li>
        <li>
            <%= f.label :medical_other do %>
                <div class="selection">
                    <%= f.check_box :medical_other, :class => 'autosave' %> Yes
                </div>Do you know of any other reason why you should not be performing physical activity?
            <% end %>
        </li>
    </ol>    
    <div class="health-notice push hide field_with_errors">
        <label class="message">Please note, as you have answered yes to 1 or more of these questions we recommend that you consult a physician prior to using Wurqit!</label>
    </div>
    <div id="health-notice-modal" class="modal hide fade">
        <div class="modal-body">
            <p>Please note, as you have answered yes to 1 or more of these questions we recommend that you consult a physician prior to using Wurqit!</p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Ok</button>
        </div>
    </div>
</div>

app/views/users/shared/settings/_wurqout_preferences.html.erb
<div class="control-group spaced">
    <%= label_tag 'What time do you prefer to work out?', nil, :class => "big" %>
    <div class="push">
        <%= f.label :wurqout_preference_morning, :class => "checkbox inline" do %>
            <%= f.check_box :wurqout_preference_morning, :class => 'autosave' %> Morning
        <% end %>
        <%= f.label :wurqout_preference_afternoon, :class => "checkbox inline" do %>
            <%= f.check_box :wurqout_preference_afternoon, :class => 'autosave' %> Afternoon
        <% end %>
        <%= f.label :wurqout_preference_evening, :class => "checkbox inline" do %>
            <%= f.check_box :wurqout_preference_evening, :class => 'autosave' %> Evening
        <% end %>
    </div>
</div>

<div class="control-group spaced">
    <%= label_tag 'What is your preferred activity level?', nil, :class => "big" %>
    <div class="push">
        <%= f.label :wurqout_preference_beginner, :class => "checkbox inline" do %>
            <%= f.check_box :wurqout_preference_beginner, :class => 'autosave' %> Beginner
        <% end %>
        <%= f.label :wurqout_preference_intermediate, :class => "checkbox inline" do %>
            <%= f.check_box :wurqout_preference_intermediate, :class => 'autosave' %> Intermediate
        <% end %>
        <%= f.label :wurqout_preference_advanced, :class => "checkbox inline" do %>
            <%= f.check_box :wurqout_preference_advanced, :class => 'autosave' %> Advanced
        <% end %>
        <%= f.label :wurqout_preference_hardcore, :class => "checkbox inline" do %>
            <%= f.check_box :wurqout_preference_hardcore, :class => 'autosave' %> Hardcore
        <% end %>
    </div>
</div>

<% if @user.role?('wurqer') %>
    <%= render 'users/shared/settings/interests', :f => f, :title => 'Interests' %>
<% end %>

<% if @user.role?('wurqer') %>
    <div class="control-group spaced">
        <%= label_tag 'Training goals (select all that apply)', nil, :class => "big" %>
        <div class="push">
            <ul class="split split3 unstyled">
                <li>
                    <%= f.label :goal_lose_weight, :class => "checkbox" do %>
                        <%= f.check_box :goal_lose_weight, :class => 'autosave' %> Lose weight
                    <% end %>

                    <%= f.label :goal_eat_right, :class => "checkbox" do %>
                        <%= f.check_box :goal_eat_right, :class => 'autosave' %> Eat right
                    <% end %>

                    <%= f.label :goal_wurqout_more, :class => "checkbox" do %>
                        <%= f.check_box :goal_wurqout_more, :class => 'autosave' %> Wurqout more
                    <% end %>

                    <%= f.label :goal_tone, :class => "checkbox" do %> 
                        <%= f.check_box :goal_tone, :class => 'autosave' %> Tone
                    <% end %>

                    <%= f.label :goal_get_stronger, :class => "checkbox" do %>
                        <%= f.check_box :goal_get_stronger, :class => 'autosave' %> Get stronger
                    <% end %>
                </li>
                <li>
                    <%= f.label :goal_increase_flexibility, :class => "checkbox" do %>
                        <%= f.check_box :goal_increase_flexibility, :class => 'autosave' %> Increase Flexibility
                    <% end %>

                    <%= f.label :goal_increase_engery, :class => "checkbox" do %>
                        <%= f.check_box :goal_increase_engery, :class => 'autosave' %> Increase energy
                    <% end %>

                    <%= f.label :goal_reduce_stress, :class => "checkbox" do %>
                        <%= f.check_box :goal_reduce_stress, :class => 'autosave' %> Reduce stress
                    <% end %>

                    <%= f.label :goal_increase_endurance, :class => "checkbox" do %>
                        <%= f.check_box :goal_increase_endurance, :class => 'autosave' %> Increase endurance
                    <% end %>

                    <%= f.label :goal_learn_how_to_excercise, :class => "checkbox" do %>
                        <%= f.check_box :goal_learn_how_to_excercise, :class => 'autosave' %> Learn how to exercise
                    <% end %>
                </li>
                <li>
                    <%= f.label :goal_look_better_naked, :class => "checkbox" do %>
                        <%= f.check_box :goal_look_better_naked, :class => 'autosave' %> Look better naked
                    <% end %>

                    <%= f.label :goal_sports_specific, :class => "checkbox" do %>
                        <%= f.check_box :goal_sports_specific, :class => 'autosave' %> Sports-specific goals
                    <% end %>
                
                    <%= f.label :goal_feel_better, :class => "checkbox" do %>
                        <%= f.check_box :goal_feel_better, :class => 'autosave' %> Feel better about myself
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
    <div class="control-group spaced">
        <%= label_tag nil, 'Are you interested in co-wurqing?', :class => "big" %>
        <div class="push">
            <%= f.label :allow_contact, :class => "checkbox inline" do %>
                <%= f.check_box :allow_contact, :class => 'autosave' %> Yes! Allow others to contact me
            <% end %>
        </div>
    </div>
<% end %>

<% if @user.role?('guru')%>
    <div class="control-group spaced">
        <%= label_tag nil, 'Session Rates', :class => "big" %>
        <div id="session_rates" class="form-horizontal">
            <div class="control-group">
                <%= f.label :guru_pricing_tier1, '15 mins', :class => "control-label" %>
                <div class="controls">
                    <span class="input-prepend">
                        <span class="add-on">$</span><%= f.text_field :guru_pricing_tier1 %>
                    </span>
                    <%= f.label :guru_pricing_tier1_enabled, :"data-noblank" => 'true', :class => "checkbox switcher inline" do %>
                        <%= f.check_box :guru_pricing_tier1_enabled, :class => 'switch autosave' %> <span class="on">Enabled</span><span class="off">Disabled</span>
                    <% end %>
                    <div class="error"><i></i><label class="message">can't be blank &amp; enabled</label></div>
                </div>
            </div>
            <div class="control-group">
                <%= f.label :guru_pricing_tier1, '30 mins', :class => "control-label" %>
                <div class="controls">
                    <span class="input-prepend">
                        <span class="add-on">$</span><%= f.text_field :guru_pricing_tier2 %>
                    </span>
                    <%= f.label :guru_pricing_tier2_enabled, :"data-noblank" => 'true', :class => "checkbox switcher inline" do %>
                        <%= f.check_box :guru_pricing_tier2_enabled, :class => 'switch autosave' %> <span class="on">Enabled</span><span class="off">Disabled</span>
                    <% end %>
                    <div class="error"><i></i><label class="message">can't be blank &amp; enabled</label></div>
                </div>
            </div> 
            <div class="control-group">
                <%= f.label :guru_pricing_tier1, '60 mins', :class => "control-label" %>
                <div class="controls">
                    <span class="input-prepend">
                        <span class="add-on">$</span><%= f.text_field :guru_pricing_tier3 %>
                    </span>
                    <%= f.label :guru_pricing_tier3_enabled, :"data-noblank" => 'true', :class => "checkbox switcher inline" do %>
                        <%= f.check_box :guru_pricing_tier3_enabled, :class => 'switch autosave' %> <span class="on">Enabled</span><span class="off">Disabled</span>
                    <% end %>
                    <div class="error"><i></i><label class="message">can't be blank &amp; enabled</label></div>
                </div>
            </div>
       </div>
   </div>

   <div class="control-group spaced">
       <%= label_tag nil, 'Set your Availability', :class => "big" %>
       <p>You can access <%= link_to 'your availability calendar', availability_path %> at any time from the user menu on the top right.</p>
       <%= link_to '<i class="icon-calendar"></i> Set your availability'.html_safe, availability_path, :class => 'btn btn-text' %>
   </div>
<% end %>