config/routes.rb
Findatech::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}

  root :to => "home#index"

  resources :users do
    collection do
      get :dashboard
      get :settings
      post :delete_photo
      post :get_my_schedule
      post :get_availability
      post :set_availability
      post :update_availability
      post :remove_availability
      get :search
    end
    get :availability
    put :change_photo
    get :profile
    get :schedule_appointment
    get :schedule
    post :update_schedule
    post :sync_to_gcal
  end

  #admin routes
  match 'admins/dashboard/' => 'admins/admin#dashboard'
  namespace :admins do
     resources :users do
       post :reset_password
       post :lock_user
       post :unlock_user
       get :set_featured_tech
     end
  end
  
end

app/views/layouts/_footer.html.erb
<div id="footer">		
		<div class="content_pad">			
			<p>&copy; 2010-11 Copyright <a href="http://madebyamp.com">Find-A-Tech New Jersey</a>. Powered by <a href="http://findatech.com">Find-A-Tech</a>.</p>
		</div> <!-- .content_pad -->
	</div> <!-- #footer -->		

app/views/layouts/_nav.html.erb
<div id="header">
		
		<div class="content_pad">
			
			
	<h1><a href="/">Dashboard</a></h1>
			
			<ul id="nav">
				<li class="nav_icon<%= " nav_current" if current_page?('/users/dashboard') %>"><a href="/users/dashboard"><span class="ui-icon ui-icon-home"></span>Home</a></li>
				
				<li class="nav_icon<%= " nav_current" if current_page?('/users/search') %>"><a href="/users/search"><span class="ui-icon"></span>Search Techs</a></li>

				<li class="nav_dropdown nav_icon<%= " nav_current" if current_page?('/appointments') %>">
					<a href="/appointments"><span class="ui-icon ui-icon-gripsmall-diagonal-se"></span>Appointments</a>
					
					<div class="nav_menu">			
						<ul>
							<li><%= link_to "New Appointments", appointments_path(:status => 'new') %></li>	
							<li><%= link_to "Unconfirmed", appointments_path(:status => 'unconfirmed')%></li>	
							<li><%= link_to "Comfirmed", appointments_path(:status => 'confirmed')%></li>	
							<li><%= link_to "Complete Appointments", appointments_path(:status => 'complete')%></li>			
						</ul>
						
					</div>
				</li>
				
				<li class="nav_dropdown nav_icon_only">
					<a href="javascript:;">&nbsp;</a>
					
					<div class="nav_menu">
						
						<ul>
							<li><a href="javascript:;">Overflow Menu</a></li>
							<li><a href="javascript:;">Items Can</a></li>
							<li><a href="javascript:;">Go Here</a></li>
						</ul>
					</div> <!-- .menu -->
				</li>
			</ul>
		</div> <!-- .content_pad -->
		
	</div> <!-- #header -->	

app/views/layouts/_topbar.html.erb
	<div id="top">
		
		<div class="content_pad">			
			<ul class="right">
				
				<li>
					<% if user_signed_in? %>
						<a href="/users/dashboard" class="top_icon"><span class="ui-icon ui-icon-person"></span>Logged in as <%= current_user.username %></a>
					<% else %>
						<a href="/users/sign_in" class="top_icon"><span class="ui-icon ui-icon-person"></span>Sign in</a>
					<%end%>
				</li>
				<li>
					<%if user_signed_in?%>
						<% if current_user.role?('user') %>
							<% @alert = Appointment.find(:all, :conditions => "status = 'unconfirmed' and user_id = #{current_user.id}")%>
						<% elsif current_user.role?('tech') %>
							<% @alert = Appointment.find(:all, :conditions => "(status = 'rescheduled' or status = 'new') and user_id = #{current_user.id}") %>
						<% end %>
							
						<% if !@alert.blank? %>
							<%= link_to @alert.length.to_s + " New Alert"+(@alert.many? ? 's' : ''), "/users/appointments", :class => 'new_messeges top_alert'%>
						<% end %>
					<% end %>
				</li>
					
				<% if user_signed_in? %>
					<li><%= link_to "Settings", settings_users_path %></li>
					<li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' %></li>
				<% end %>
			</ul>
		</div> <!-- .content_pad -->
		
	</div> <!-- #top -->	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Findatech</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
	
	<%= render 'layouts/topbar' %>
	<% if user_signed_in? %>
		<%= render 'layouts/nav'%>
	<%end%>
	<div id="content" class="xgrid">
	
		<% flash.each do |name, msg| %>
            <%= content_tag :p, msg, :class => "alert alert-error flash_#{name}" if msg.length > 0 %>
        <% end %>
	
	<%= yield %>
	
	</div>
	
	<%= render 'layouts/footer'%>

</div> <!-- #wrapper -->

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Findatech</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "home" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
	
	<%= render 'layouts/topbar' %>
	
	<% if user_signed_in? %>
		<%= render 'layouts/nav'%>
	<%end%>
	
	<div id="content" class="xgrid">
	
	<%= yield %>
	
	</div>
	
	<%= render 'layouts/footer'%>

</div> <!-- #wrapper -->

</body>
</html>